#############################################################################
# Makefile for building: bin/simulator
# Generated by qmake (2.01a) (Qt 4.8.1) on: ?? ???. 6 14:03:46 2016
# Project:  simulator.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile simulator.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Iobj -Iobj -Iobj
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lwfdb -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/delegate.cpp \
		src/qcustomplot.cpp obj/moc_simulator.cpp \
		obj/moc_delegate.cpp \
		obj/moc_qcustomplot.cpp \
		obj/qrc_application.cpp
OBJECTS       = obj/main.o \
		obj/delegate.o \
		obj/qcustomplot.o \
		obj/moc_simulator.o \
		obj/moc_delegate.o \
		obj/moc_qcustomplot.o \
		obj/qrc_application.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		simulator.pro
QMAKE_TARGET  = simulator
DESTDIR       = bin/
TARGET        = bin/simulator

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): obj/ui_simulator.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: simulator.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile simulator.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile simulator.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/simulator1.0.0 || $(MKDIR) obj/simulator1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/simulator1.0.0/ && $(COPY_FILE) --parents src/simulator.h src/delegate.h src/qcustomplot.h obj/simulator1.0.0/ && $(COPY_FILE) --parents img/application.qrc obj/simulator1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/delegate.cpp src/qcustomplot.cpp obj/simulator1.0.0/ && $(COPY_FILE) --parents ui/simulator.ui obj/simulator1.0.0/ && (cd `dirname obj/simulator1.0.0` && $(TAR) simulator1.0.0.tar simulator1.0.0 && $(COMPRESS) simulator1.0.0.tar) && $(MOVE) `dirname obj/simulator1.0.0`/simulator1.0.0.tar.gz . && $(DEL_FILE) -r obj/simulator1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: obj/moc_simulator.cpp obj/moc_delegate.cpp obj/moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_simulator.cpp obj/moc_delegate.cpp obj/moc_qcustomplot.cpp
obj/moc_simulator.cpp: src/simulator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/simulator.h -o obj/moc_simulator.cpp

obj/moc_delegate.cpp: src/delegate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/delegate.h -o obj/moc_delegate.cpp

obj/moc_qcustomplot.cpp: src/qcustomplot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qcustomplot.h -o obj/moc_qcustomplot.cpp

compiler_rcc_make_all: obj/qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) obj/qrc_application.cpp
obj/qrc_application.cpp: img/application.qrc \
		img/noise.png \
		img/graph.png \
		img/stop.png \
		img/exit.png \
		img/start.png \
		img/add.png \
		img/1.png \
		img/play.png \
		img/2.png \
		img/lines.png \
		img/save.png \
		img/3.png \
		img/record.png \
		img/remove.png \
		img/edit.png \
		img/pause.png \
		img/open.png
	/usr/bin/rcc -name application img/application.qrc -o obj/qrc_application.cpp

compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: obj/ui_simulator.h
compiler_uic_clean:
	-$(DEL_FILE) obj/ui_simulator.h
obj/ui_simulator.h: ui/simulator.ui \
		src/qcustomplot.h
	/usr/bin/uic-qt4 ui/simulator.ui -o obj/ui_simulator.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp src/simulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/delegate.o: src/delegate.cpp src/delegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/delegate.o src/delegate.cpp

obj/qcustomplot.o: src/qcustomplot.cpp src/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qcustomplot.o src/qcustomplot.cpp

obj/moc_simulator.o: obj/moc_simulator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_simulator.o obj/moc_simulator.cpp

obj/moc_delegate.o: obj/moc_delegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_delegate.o obj/moc_delegate.cpp

obj/moc_qcustomplot.o: obj/moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qcustomplot.o obj/moc_qcustomplot.cpp

obj/qrc_application.o: obj/qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_application.o obj/qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

